logoText = "Gictor" # Logo text that appears in the site navigation bar.
logoType = "short" # long, short -> short: squre shape includes logo text, long: rectangle shape not includes logo text
logo = true # Logo that appears in the site navigation bar.
description = "The victor personal blog" # for SEO
custom_css = ["css/font.css"] # custom_css = ["scss/custom.scss"] and then make file at root/assets/scss/custom.scss
custom_js = [] # custom_js = ["js/custom.js"] and then make file at root/assets/js/custom.js
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = "/images/whoami/avatar.jpg"

authorImage = "/images/whoami/avatar.jpg"
author = "victor"

themeOptions = ["dark"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

enableUiAnimation = false

# header
homeHeaderType = "empty" # text, img, slide

# menu 
showMobileMenuTerms = ["tags", "series"] #["tags", "categories", "series"]

# body
enableBreadcrumb = true # breadcrumb for list, single page
enableSearch = true # site search with Fuse
enableSearchHighlight = true # when true, search keyword will be highlighted
enableGoToTop = true # scroll to top
enableWhoami = false # at the end of single page
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13 # items per page
paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc
talksPaginate = 8 # items per page
talksGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
pubPaginate = 20
searchResultPosition = "side" # side, main


# sidebar
enableBio = true # home page sidebar
enableSidebar = true # Set to false to create the full width of the content.
enableSidebarTags = true # if you want to use tags.
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true # single page table of contents, you can replace this param to toc(toc = true)
sidebarPosition = "right" # bio, profile component layout position
hideToc = false # Hide or Show toc
tocFolding = false
tocPosition = "inner" # inner, outer
enableTocSwitch = true # single page table of contents visibility switch
itemsPerCategory = 5 # maximum number of posts shown in the sidebar.
enableSidebarPostsByOrder = false
tocLevels = ["h2", "h3", "h4"]

# footer
showPoweredBy = false # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed 
showSocialLinks = true # email, facebook, twitter ...
enableLangChange = true # show button at bottom left of footer.
enableThemeChange = true # site color theme

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = "" # alternative of google analytics
enableBusuanzi = true # if set true, total page view, total unique visitors show up in the footer.
busuanziSiteUV = false # unique visitors (total number of visitors)
busuanziSitePV = false # site total page view count
busuanziPagePV = true # post view count

# rss
updatePeriod = "daily" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false


[copyrightOptions]
  enableCopyrightLink = true # if set, you can add copyright link
  copyrightLink = "https://creativecommons.org/licenses/by-nc/4.0/"
  copyrightLinkImage = "https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-nc.svg"
  copyrightLinkText = "CC BY-NC"

# possible share name: "facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "whatsapp", "telegram"
[[share]]
  name = "facebook"
  username = "gictorbit"
[[share]]
  name = "twitter"
  username = "gictorbit"
[[share]]
  name = "telegram"
[[share]]
  name = "whatsapp"
[[share]]
  name = "linkedin"
[[share]]
  name = "reddit"

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""

