# Site settings
baseurl = "/"
title = "Oblate"
themesDir = "themes"
theme = "hugo"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[taxonomies]
  category = "categories"

