#SectionPagesMenu = "main"
# Site settings
baseurl = "https://www.tahmil.me/"
languageCode = "ar-SA"
DefaultContentLanguage = "ar"
title = "تحميل"
theme = "Geek"
paginate = 6
canonifyURLs = true

[sitemap]
    changefreq = "weekly"
    priority = 0.9
	filename = "map.xml"
	
[taxonomies]
   category = "categories"
   tag = "tags"
   
[permalinks]
  posts  = "/:slug/"
  pages = "/:filename/"
  categories = "/:title/" 


[Author]
  name = "Sam Hamou"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "الرئيسية"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "برامج ويندوز"
    url = "/windows"
    weight = 2
  [[menu.main]]
    name = "برامج ماكنتوش"
    url = "/mac"
    weight = 3
  [[menu.main]]
    name = "برامج أندرويد"
    url = "/android"
    weight = 4
  [[menu.main]]
    name = "برامج آيفون"
    url = "/ios"
    weight = 5
   [[menu.main]]
    identifier = "category"
    name = "المزيد"
    weight = 6
  [[menu.main]]
    identifier = "category1"
    name = "عن الموقع"
    url = "/about"
    parent = "category"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "أعلن معنا"
    url = "/ads"
    parent = "category"
    weight = 2
  [[menu.main]]
    identifier = "category3"
    name = "إتصل بنا"
    url = "/contact"
    parent = "category"
    weight = 3
   [[menu.main]]
    identifier = "category4"
    name = "سياسة الخصوصية"
    url = "/privacy"
    parent = "category"
    weight = 4

