#hasCJKLanguage = true
baseurl = "https://www.tahmil.me/"
anguageCode = "ar-SA"
DefaultContentLanguage = "ar"
title = "تحميل"
theme = "UP"
author = "تحميل"
canonifyURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.9
  filename = "map.xml"

[permalinks]
  posts = "/:slug/"
  pages = "/:filename/"
  categories = "/:title/" 

[params]
  description = "هل تتطلع إلى تنزيل إصدارات مجانية آمنة من أحدث البرامج والتطبيقات من موقع تنزيل موثوق به؟ قم بزيارتنا اليوم. " 
  mainSections = [ "posts" ]
  paginator_pages = "7"
  tagsLimit = 15

[params.widgets]
  recentposts = false
  archives = false
  categories = true
  tags = true
  search = true
    
[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  
  
[params.post]
  # See the Tailwind CSS documentation to set it up.
  # Recommended settings are h-32 to h-48.
  # https://tailwindcss.com/docs/height
    thumbnail_height = "h-auto"

  # https://tailwindcss.com/docs/width
    thumbnail_width = "w-56"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "الرئيسية"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "عن الموقع"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "إتصل بنا"
    url = "/contact/"
    weight = 3
	
	[[menu.main]]
    identifier = "privacy"
    name = "الخصوصية"
    url = "/privacy/"
    weight = 4


[build]
  writeStats = true

