# Site settings
baseurl = "/"
title = "Arafeed"
themesDir = "themes"
theme = "Feed"
paginate = 6
assetDir = "static"

summarylength = 10
hasCJKLanguage = true 


[Author] # Default Author
  code = "SamHamou"
  name = "Sam Hamou"
  
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "الرئيسية"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "برامج ويندوز"
    url = "/windows"
    weight = 2
  [[menu.main]]
    name = "برامج ماكنتوش"
    url = "/mac"
    weight = 3
  [[menu.main]]
    name = "برامج أندرويد"
    url = "/android"
    weight = 4
  [[menu.main]]
    name = "برامج آيفون"
    url = "/ios"
    weight = 5
  


[Params]
  subtitle = "Ashish Lahoti's Technical Blog" # Subtitle of your site. Used in site header
  description = "Coding N Concepts is a technical blog for developers by developers to help you with coding problems, puzzle-solving, interview preparation, learning concepts in a simplified way." # Site description. Used in meta description
  logo = "/img/favicon.ico"
  copyright = "Arafeed" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["author", "categories"] # Order of post meta information
  mainSections = ["posts", "anothersection"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 02, 2006" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files
  
[Params.socialshare]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  search = "right"
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[taxonomies]
   tag = "tags"
   category = "categories" 

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4



  
