# Site settings
baseurl = "https://arafeed.netlify.app/"
languageCode = "en-us"
title = "Oblate"
theme = "hugo"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[taxonomies]
  category = "categories"


[outputs]
home = ["HTML", "RSS"]
