# Site settings
baseurl = "https://www.tahmil.me/"
languageCode = "ar-SA"
DefaultContentLanguage = "ar"
title = "تحميل"
theme = "One"
paginate = 6
canonifyURLs = true

[sitemap]
    changefreq = "weekly"
    priority = 0.9
	filename = "map.xml"
	
[permalinks]
posts = "/:slug/"
pages = "/:slug/"
categories = "/:title/" 

[params]
mainSections = [ "posts" ]
featuredImageField = "image"
rssFullContent = true
favicon = true


  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  subtitle = "تحميل الانمي برابط واحد"

    [params.sidebar.avatar]
    local = true
    src = "img/avatar.jpg"

  [params.article]
  math = false



  
  [params.widgets]
  enabled = [ "search", "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5
    path = "archives"

    [params.widgets.tagCloud]
    limit = 10

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "الرئيسية"
url = "/"
weight = -100
pre = "home"

[[menu.main]]
identifier = "about"
name = "عن الموقع"
url = "about"
weight = -90
pre = "user"

[[menu.main]]
identifier = "archives"
name = "الأرشيف"
url = "archives"
weight = -70
pre = "archives"

[[menu.main]]
identifier = "search"
name = "البحث"
url = "search"
weight = -60
pre = "search"

  [[menu.main]]
    name = "برامج ويندوز"
    url = "/windows"
    weight = 2
  [[menu.main]]
    name = "برامج ماكنتوش"
    url = "/mac"
    weight = 3
  [[menu.main]]
    name = "برامج أندرويد"
    url = "/android"
    weight = 4
  [[menu.main]]
    name = "برامج آيفون"
    url = "/ios"
    weight = 5
  


[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.highlight]
noClasses = false