baseURL = "/"
languageCode = "ar-SA"
DefaultContentLanguage = "ar"
title = "arafeed"
theme = "arafeed"
paginate = 5
enableRobotsTXT = "true"
canonifyURLs = true
#SectionPagesMenu = "main"

summarylength = 45
hasCJKLanguage = true 

[permalinks]
  posts  = "/:slug/"
  pages = "/:filename/"
  categories = "/:title/"
  
[taxonomies]
   tag = "tags"
   category = "categories"  


[params]
  metaDescription = ""
  keywords = ""
  googleAnalytics = ""
  customCSS = []

  twitterName = "sam_hamou"
  RSSLink = "/"


  logo = "logo.webp"
  orgName = "Mofeed"
  orgWebsite = "/"
  orgDescription = ""

  author = "Sam Hamou"
  authorAvatar = "avatar.webp"
  authorLocation = "Morocco"
  authorWebsite = "/"
  authorDescription = " مطور ويب مستقل متخصص في الواجهات الأمامية، وصانع محتوى."

  pageNotFoundTitle = "هذه الصفحة غير موجودة"

 



[[menu.main]]
  name = "الرئيسية"
  url = "/"
  weight = 200

[[menu.main]]
  name = "قوالب"
  url = "/templates/"
  weight = 100

[[menu.main]]
  name = "مقالات"
  url = "/articles/"
  weight = 99

[[menu.main]]
  name = "برامج"
  url = "/software/"
  weight = 95


