baseURL = "https://arafeed.netlify.app/"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 12
summaryLength = 140
title = "Arafeed"

[permalinks]
  post  = "/:slug/"
  pages = "/:filename/"
  categories = "/:title/"
  
[taxonomies]
   tag = "tags"
   category = "categories"    
